spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
    application: 
    name: Democonfig-test-dev
    
---
spring:
  profiles: default
    application: 
     name: Democonfig-test-default